name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "needs-triage"]
body:
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package does this relate to?
      options:
        - "@peripheral/ble-core"
        - "@peripheral/smart-home"
        - "@peripheral/gesture-engine"
        - "@peripheral/integration"
        - "Monorepo / Build tooling"
        - "New package"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What use case is not currently supported?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature or API you would like to see. Include code examples if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you have considered, including workarounds you are currently using.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or references.
    validations:
      required: false
